blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://unix.stackexchange.com/questions/tagged/v4l2loopback
    about: For general questions (and answers) about the usage of this module, please check the `v4l2loopback` tag on *StackExchange*
  - name: Look for more Documentation
    url: https://github.com/umlaeute/v4l2loopback/wiki
    about: Check our WIKI to see whether your question has already been answered.
